// Generated by CoffeeScript 1.6.1

/* VALIDATINS
*/


(function() {
  var CountryValid, DOBValid, FirstNameValid, HobbiesValid, LastNameValid, MobileValid, PasswordValid, ProfileValid, ProgressDec, ProgressInc, UserNameValid, Validations, error, success;

  $(function() {
    return $('#reg').submit(function() {
      return Validations();
    });
  });

  Validations = function() {
    var CountryCheck, DOBCheck, FNameCheck, HobbiesCheck, LNameCheck, MobileCheck, PasswordCheck, ProfpicCheck, UserCheck;
    UserCheck = UserNameValid();
    PasswordCheck = PasswordValid();
    FNameCheck = FirstNameValid();
    LNameCheck = LastNameValid();
    ProfpicCheck = ProfileValid();
    DOBCheck = DOBValid();
    HobbiesCheck = HobbiesValid();
    MobileCheck = MobileValid();
    CountryCheck = CountryValid();
    if (UserCheck === true && PasswordCheck === true && FNameCheck === true && LNameCheck === true && ProfpicCheck === true && DOBCheck === true && HobbiesCheck === true && MobileCheck === true && CountryCheck === true) {
      $("#SuccessMsg").css("display", "block");
      return false;
    } else {
      return false;
    }
  };

  /*******************USERNAME VALIDATION ******************
  */


  $("#inputName").bind("blur", function() {
    return UserNameValid();
  });

  UserNameValid = function() {
    var AlphaNumPatt, Name;
    Name = $("#inputName").val();
    AlphaNumPatt = /^[0-9A-z]+$/;
    if (Name.length >= 5) {
      if (AlphaNumPatt.test(Name)) {
        return success("UserMsg");
      } else {
        return error("UserMsg");
      }
    } else {
      return error("UserMsg");
    }
  };

  /*******************PASSWORD VALIDATION ******************
  */


  $("#inputPassword").bind("blur", function() {
    return PasswordValid();
  });

  PasswordValid = function() {
    var AlphaNumPatt, Password;
    Password = $("#inputPassword").val();
    AlphaNumPatt = /^[0-9A-z]+$/;
    if (AlphaNumPatt.test(Password)) {
      return success("PasswordMsg");
    } else {
      return error("PasswordMsg");
    }
  };

  /***********FIRSTNAME VALIDATION ****************
  */


  $("#inputFirstName").bind("blur", function() {
    return FirstNameValid();
  });

  FirstNameValid = function() {
    var fName;
    fName = $("#inputFirstName").val();
    if (fName.length < 2) {
      return error("FirstNameMsg");
    } else {
      return success("FirstNameMsg");
    }
  };

  /****************LASTNAME VALIDATION *******
  */


  $("#inputLastName").bind("blur", function() {
    return LastNameValid();
  });

  LastNameValid = function() {
    var lName;
    lName = $("#inputLastName").val();
    if (lName.length < 2) {
      return error("LastNameMsg");
    } else {
      return success("LastNameMsg");
    }
  };

  /************DOB VALIDATION ************
  */


  $("#Date").on("change", function() {
    return DOBValid();
  });

  $("#Month").on("change", function() {
    return DOBValid();
  });

  $("#Year").on("change", function() {
    return DOBValid();
  });

  DOBValid = function() {
    var selectDate, selectMonth, selectYear;
    selectDate = $("#Date").val();
    selectMonth = $("#Month").val();
    selectYear = $("#Year").val();
    if (selectDate == "-- Date --" || selectMonth == "-- Month --" || selectYear == "-- Year --") {
      return error("DOBMsg");
    } else {
      return success("DOBMsg");
    }
  };

  /*************HOBBIES VALIDATION *************
  */


  $("#h1").on("change", function() {
    return HobbiesValid();
  });

  $("#h2").on("change", function() {
    return HobbiesValid();
  });

  $("#h3").on("change", function() {
    return HobbiesValid();
  });

  $("#h4").on("change", function() {
    return HobbiesValid();
  });

  $("#h5").on("change", function() {
    return HobbiesValid();
  });

  HobbiesValid = function() {
    var hob1, hob2, hob3, hob4, hob5;
    hob1 = $("#h1").prop('checked');
    hob2 = $("#h2").prop('checked');
    hob3 = $("#h3").prop('checked');
    hob4 = $("#h4").prop('checked');
    hob5 = $("#h5").prop('checked');
    if (hob1 === true || hob2 === true || hob3 === true || hob4 === true || hob5 === true) {
      return success("HobbiesMsg");
    } else {
      return error("HobbiesMsg");
    }
  };

  /*******************PROFILEPIC VALIDATION **************
  */


  $("#inputFile").on("change", function() {
    return ProfileValid();
  });

  ProfileValid = function() {
    var pic;
    pic = $("#inputFile").val();
    if ((pic == null) || pic === "") {
      return error("ProfileMsg");
    } else {
      return success("ProfileMsg");
    }
  };

  /*************************PHONE VALIDATION *********************
  */


  $("#inputPhone").bind("blur", function() {
    return MobileValid();
  });

  MobileValid = function() {
    var MobPatt, Phone;
    Phone = $("#inputPhone").val();
    MobPatt = /^([+][0-9]\d{1}) ([(][0-9]\d{2}[)])-([0-9]\d{2})-([0-9]\d{3})$/;
    if (MobPatt.test(Phone)) {
      return success("MobileMsg");
    } else {
      return error("MobileMsg");
    }
  };

  /************COUNTRY VALIDATION ***********
  */


  $("#Country").bind("blur", function() {
    return CountryValid();
  });

  CountryValid = function() {
    var Country;
    Country = $("#Country").val();
    if (Country == "-- Country --") {
      return error("CountryMsg");
    } else {
      return success("CountryMsg");
    }
  };

  /**************************** SUCCESS AND ERROR ***************************
  */


  success = function(id) {
    var clsName;
    clsName = $("#" + id).prop("className");
    $("#" + id).attr('class', 'success');
    if (clsName !== "success") {
      ProgressInc();
    }
    return true;
  };

  error = function(id) {
    var clsName;
    clsName = $("#" + id).prop("className");
    $("#" + id).attr('class', 'error');
    if (clsName !== "error" && clsName !== "NameMsg") {
      ProgressDec();
    }
    return false;
  };

  /******************************* PROGRESS BAR ********************************
  */


  ProgressInc = function() {
    var pb;
    pb = $("#progress").val();
    $("#progress").val(pb + 1);
    return $("#percent").text((pb + 1) * 10 + "%");
  };

  ProgressDec = function() {
    var pb;
    pb = $("#progress").val();
    $("#progress").val(pb - 1);
    return $("#percent").text((pb - 1) * 10 + "%");
  };

}).call(this);
